{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nemoclaw.fullname" . }}-agent-state
  labels:
    {{- include "nemoclaw.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- $sc := include "nemoclaw.storageClass" . }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
